INSERT INTO agent_log (account_id, agent_id, contact_session_id, queue_id, campaign_id,
                       contact_id, meta_status_id, channel, date, call_wrapup_id,
                       conference_id, activity_id, ref_activity_id, agent_session_id,
                       mail_id, mail_wrapup_id, mail_wrapup_duration_ms, thread_id,
                       abr, warm_transfer, display_number_id, campaign_wrapup_final,
                       service_id, user_number_type, user_phone_number)
SELECT (random() * 1000)::int, (random() * 1000)::int, gen_random_uuid(),
       (random() * 100)::int, (random() * 100)::int, (random() * 10000)::int, (random() * 100)::int,
        (ARRAY['NONE',
        'INBOUND',
        'OUTBOUND',
        'FREE_CALL',
        'CHAT', 'EMAIL',
        'AGENT_CALL',
        'EMAIL_OUTBOUND',
        'SALESFORCE',
        'SMS',
        'WHATSAPP'])[floor(random()*11 + 1)]::channel_enum,
    now() - (random() * interval '30 days'),
    (random() * 1000)::int,
    gen_random_uuid(),
    (random() * 1000)::int,
    (random() * 1000)::int,
    gen_random_uuid(),
    (random() * 1000)::int,
    (random() * 1000)::int,
    (random() * 10000)::bigint,
    (random() * 10000)::int,
    (random() > 0.5),
    (random() > 0.5),
    (random() * 100)::int,
    (random() > 0.5),
    (random() * 1000)::int,
    'mobile',
    '+33123456789'
FROM generate_series(1, 500);

INSERT INTO contact_log (contact_session_id, queue_id, agent_id, date, channel, campaign_contact_id,
                         campaign_id, conference_id, contact_phone, service_phone, call_result,
                         record_file_name, record_is_explicitly_started, record_file_name_displayed,
                         activity_id, agent_session_id, displayed_number, record_is_voice_message,
                         external_storage_id, displayed_number_id, payment_result_detail, payment_id,
                         abr, warm_transfer, ref_activity_id, ref_queue_id, discard_left_audio_channel,
                         discard_right_audio_channel, call_lid)
SELECT gen_random_uuid(),
       (random() * 100)::int, (random() * 1000)::int, now() - (random() * interval '30 days'),
       (ARRAY[
            'NONE', 'INBOUND', 'OUTBOUND', 'FREE_CALL', 'CHAT', 'EMAIL',
        'AGENT_CALL', 'EMAIL_OUTBOUND', 'SALESFORCE', 'SMS', 'WHATSAPP'
            ])[floor(random() * 11)::int + 1]::channel_enum,
    (random() * 1000)::int,
    (random() * 1000)::int,
    gen_random_uuid(),
    '+33123456789',
    '+33987654321',
    (ARRAY['CONNECTED', 'ABANDON', 'ANSWERING_MACHINE', 'UNALLOCATED', 'BUSY', 'NO_ANSWER', 'OTHER', 'HANDLED',
    'ABANDON_QUEUE', 'CALENDAR_CLOSED', 'DISSUASION_IVR',
    'ABANDON_IVR', 'DISSUASION_NO_AGENT', 'DISSUASION_EFFECTIVE_TIMEOUT'])[floor(random()*14 + 1)]::call_result,
    'rec.wav',
    (random() > 0.5),
    'rec_display.wav',
    (random() * 1000)::int,
    gen_random_uuid(),
    '0123456789',
    (random() > 0.5),
    (random() * 1000)::int,
    (random() * 1000)::int,
    'OK',
    (random() * 10000)::int,
    (random() > 0.5),
    (random() > 0.5),
    (random() * 1000)::int,
    (random() * 100)::int,
    (random() > 0.5),
    (random() > 0.5),
    (random() * 99999999)::bigint
FROM generate_series(1, 500);

INSERT INTO mail_log (account_id, agent_id, activity_id, queue_id, service_id,
                      thread_id, contact_session_id, mail_id, date, channel,
                      ref_agent_id, ref_queue_id, from_address, to_address,
                      cc_address, bcc_address, threshold_response_date,
                      target_response_date, abr, mail_topic)
SELECT (random() * 1000)::int, (random() * 1000)::int, (random() * 1000)::int, (random() * 100)::int, (random() * 1000)::int, (random() * 10000)::int, gen_random_uuid(),
       (random() * 10000)::int, now() - (random() * interval '30 days'),
       (ARRAY[
            'NONE', 'INBOUND', 'OUTBOUND', 'FREE_CALL', 'CHAT', 'EMAIL',
        'AGENT_CALL', 'EMAIL_OUTBOUND', 'SALESFORCE', 'SMS', 'WHATSAPP'
            ])[floor(random() * 11)::int + 1]::channel_enum,
    (random() * 1000)::int,
    (random() * 1000)::int,
    'from@example.com',
    'to@example.com',
    'cc@example.com',
    'bcc@example.com',
    now() + (random() * interval '1 day'),
    now() + (random() * interval '2 days'),
    (random() > 0.5),
    'Test mail topic'
FROM generate_series(1, 500);
